// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (id, book, quote, inserted_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, book, quote, inserted_at, updated_at
`

type CreateQuoteParams struct {
	ID         uuid.UUID
	Book       string
	Quote      string
	InsertedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.ID,
		arg.Book,
		arg.Quote,
		arg.InsertedAt,
		arg.UpdatedAt,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Book,
		&i.Quote,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
